-- AlterTable
ALTER TABLE "assets" ADD COLUMN "externalLegacyId" TEXT;
ALTER TABLE "assets" ADD COLUMN "quantity" INTEGER NOT NULL DEFAULT 1;

-- CreateIndex
CREATE UNIQUE INDEX "assets_externalLegacyId_key" ON "assets"("externalLegacyId");

-- CreateEnum
CREATE TYPE "ImportStrategy" AS ENUM ('UPSERT', 'INSERT_ONLY', 'DRY_RUN');

-- CreateEnum
CREATE TYPE "ImportBatchStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "ImportRowStatus" AS ENUM ('VALID', 'CREATED', 'UPDATED', 'SKIPPED', 'ERROR');

-- CreateTable
CREATE TABLE "import_batches" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "fileName" TEXT NOT NULL,
    "fileHash" TEXT,
    "strategy" "ImportStrategy" NOT NULL DEFAULT 'UPSERT',
    "status" "ImportBatchStatus" NOT NULL DEFAULT 'PENDING',
    "totalRows" INTEGER NOT NULL DEFAULT 0,
    "processedRows" INTEGER NOT NULL DEFAULT 0,
    "createdRows" INTEGER NOT NULL DEFAULT 0,
    "updatedRows" INTEGER NOT NULL DEFAULT 0,
    "skippedRows" INTEGER NOT NULL DEFAULT 0,
    "errorRows" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "createdByUserId" INTEGER,
    "processedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "import_batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "import_batch_items" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "batchId" INTEGER NOT NULL,
    "rowNumber" INTEGER NOT NULL,
    "externalLegacyId" TEXT,
    "assetId" INTEGER,
    "status" "ImportRowStatus" NOT NULL DEFAULT 'VALID',
    "action" TEXT,
    "rawData" JSONB NOT NULL,
    "changeSet" JSONB,
    "errorMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "import_batch_items_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "import_batches_createdByUserId_idx" ON "import_batches"("createdByUserId");

-- CreateIndex
CREATE INDEX "import_batches_status_idx" ON "import_batches"("status");

-- CreateIndex
CREATE INDEX "import_batch_items_batchId_idx" ON "import_batch_items"("batchId");

-- CreateIndex
CREATE INDEX "import_batch_items_assetId_idx" ON "import_batch_items"("assetId");

-- CreateIndex
CREATE INDEX "import_batch_items_status_idx" ON "import_batch_items"("status");

-- AddForeignKey
ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_batch_items" ADD CONSTRAINT "import_batch_items_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "import_batches"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_batch_items" ADD CONSTRAINT "import_batch_items_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE SET NULL ON UPDATE CASCADE;
